version: "3"
services:

  postgres:
    container_name: "postgres-pokemon-api-java"
    image: postgres:latest
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pokemon-api-java

  pokemon-api-java:
    container_name: "pokemon-api-java"
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'